### ISSUE TITLE
Split out library to its own repository

### ISSUE THREAD

**Issue by ToniCorinne** [sparkfun/Si7021_Breakout#10]
So we can add it to the Arduino library manager.

**Comment by donnyr3** [comment]
SparkFun claims this can be downloaded in the Arduino library manager, but it can't .
Needs to be split out to its own repository.

**Comment by matthijskooijman** [comment]
I can't find this library in the manager, nor any issues in the Arduino repo requesting its inclusion, so the library does not seem to be in the manager now. And I also believe it needs a separate repository to allow inclusion. If at all possible, it would be great to have this library included in the manager.

**Comment by JoelEB** [comment]
Issue has been filed for Arduino Library manager, should be available in the Library manger soon.
