### ISSUE TITLE
Wrong temperature calculation?

### ISSUE THREAD

**Issue by hinzundcode** [sparkfun/Si7021_Breakout#11]
At [line 89 in SparkFun_Si7021_Breakout_Library.cpp](https://github.com/sparkfun/Si7021_Breakout/blob/master/Libraries/Arduino/Si7021/src/SparkFun_Si7021_Breakout_Library.cpp#L89) the constant 175.25 is used for calculating the temperature but the datasheet of the Si7021 states 175.72.

**Comment by cmfrancis** [comment]
Fixed!
