### ISSUE TITLE
Inconsistent license information

### ISSUE THREAD

**Issue by matthijskooijman** [sparkfun/Si7021_Breakout#13]
Regarding the code/library license, the [main README](https://github.com/sparkfun/Si7021_Breakout), [library README](https://github.com/sparkfun/Si7021_Breakout/blob/master/Libraries/Arduino/Si7021/README.md) and [library LICENSE file](https://github.com/sparkfun/Si7021_Breakout/blob/master/Libraries/Arduino/Si7021/LICENSE.md) talks about "beerware" and "Use as you see fit", but the source code contains a GPL license, which is distinctly different.

Regarding the hardware, the [main README](https://github.com/sparkfun/Si7021_Breakout), [library README](https://github.com/sparkfun/Si7021_Breakout/blob/master/Libraries/Arduino/Si7021/README.md) and [main LICENSE](https://github.com/sparkfun/Si7021_Breakout/blob/master/LICENSE.md) talk about CC-SA 4.0, but the  [library LICENSE file](https://github.com/sparkfun/Si7021_Breakout/blob/master/Libraries/Arduino/Si7021/LICENSE.md)  talks about CC-SA 4.0.

I'm assuming the code license is GPL, as mentioned in the code itself, and the hardware is CC-SA 4.0?

**Comment by JoelEB** [comment]
All the correct license information can now be found in the License file. Thanks for pointing out those inconsistencies.
