### ISSUE TITLE
ATtiny 85/84 board support

### ISSUE THREAD

**Issue by bidyutper** [sparkfun/Si7021_Breakout#16]
Is there any chance to run in Attiny microcontroller?

**Comment by Grahldg** [comment]
It should be possible.  A quick [Google search](https://www.google.com/search?rlz=1C1GCEA_enUS804US804&ei=qw5SW_K7HMv4tAWn3KqgBw&q=i2c+on+attiny85&oq=i2c+on+attin&gs_l=psy-ab.3.0.0j0i22i30k1l9.3552.6864.0.7857.15.12.3.0.0.0.159.902.9j2.11.0..2..0...1.1.64.psy-ab..1.14.909...0i273k1j0i67k1j0i22i10i30k1.0.gzS1WGeNbMw) yielded various results of ATtiny85 based Arduinos using I2C.  We don't currently sell any ATtiny-based Arduinos suitable for such an implementation, so it is beyond the purview of this tutorial.  If you decide to pursue this and run into any issues, you can always contact our [Technical Support Team](https://www.sparkfun.com/technical_assistance).
