### ISSUE TITLE
version 1.0.1 is published but not in this repo

### ISSUE THREAD

**Issue by tedder** [sparkfun/Si7021_Breakout#18]
I assume there's a sparkfun private repo that gets pushed to this repo. The `library.properties` indicates version 1.0.0, but 1.0.1 is in the wild- e.g., has been published. That makes it hard to track down possible problems and to know if pull requests would be honored here.

**Comment by nseidle** [comment]
Hi tedder - We've stopped keeping libraries inside hardware repos for this reason. Sorry for the confusion. The most up to date lib can be gotten from the Arduino library manager or from the [repo](https://github.com/sparkfun/SparkFun_Si701_Breakout_Arduino_Library). Please re-open if I'm missing something.

**Comment by nseidle** [comment]
I've removed the library directory from this repo.

**Comment by tedder** [comment]
thanks :) google was leading me here.

**Comment by nseidle** [comment]
![image](https://user-images.githubusercontent.com/117102/50028809-11a1aa00-ffae-11e8-9f5f-60de61e72acb.png)
