### ISSUE TITLE
No need to wait for data after Wire.requestFrom()

### ISSUE THREAD

**Issue by Koepel** [sparkfun/Si7021_Breakout#9]
In one place in SparkFun_Si7021_Breakout_Library.cpp, there is a while-loop with a delay after the Wire.requestFrom() call. That while-loop is not needed and that delay is not needed.

When the Wire.requestFrom() function returns, the I2C transaction has completely finished and the received data is in the receive buffer in the Wire library. The Wire.read() only reads data from that buffer.

**Comment by JoelEB** [comment]
Can you please point out the line on which this is happening or create a pull request with the corrected code.

**Comment by Koepel** [comment]
At this moment, the delay(1) is at line 204 [(line 204)](https://github.com/sparkfun/Si7021_Breakout/blob/master/Libraries/Arduino/Si7021/src/SparkFun_Si7021_Breakout_Library.cpp#L204).

The while-loop with the counter and the delay could be removed. When a bus error occurs or the sensor is not connected, then Wire.available() would probably return zero. That can be tested (as it is tested now), but the timeout is not needed.

```
Wire.requestFrom(ADDRESS,nBytes);
if(Wire.available() != nBytes)
  return 100;
```

**Comment by JoelEB** [comment]
Fixed here. I'll address the Arduino Library repo as well. Thanks for the feedback!
